# Generated by Django 4.2.30 on 2026-04-25 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['area', 'nombre'], 'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.RemoveField(
            model_name='anoescolar',
            name='activo',
        ),
        migrations.AddField(
            model_name='anoescolar',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('cerrado', 'Cerrado'), ('pendiente', 'Pendiente')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='colegio',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='colegio',
            name='dane',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='colegio',
            name='departamento',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='colegio',
            name='resolucion',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='colegio',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='_genero',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='eps',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='numero_documento',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('RC', 'Registro Civil'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte')], default='RC', max_length=5),
        ),
        migrations.AddField(
            model_name='estudiantepadre',
            name='es_principal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='abreviatura',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='materia',
            name='area',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='materia',
            name='intensidad_horaria',
            field=models.IntegerField(default=0, help_text='Horas semanales'),
        ),
        migrations.AddField(
            model_name='padrefamilia',
            name='numero_documento',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='padrefamilia',
            name='ocupacion',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='padrefamilia',
            name='tipo_documento',
            field=models.CharField(default='CC', max_length=5),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Observador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('positivo', 'Acto Positivo'), ('negativo', 'Acto Negativo'), ('llamado', 'Llamado de Atención'), ('academico', 'Observación Académica'), ('faltas', 'Registro de Faltas')], default='positivo', max_length=20)),
                ('gravedad', models.CharField(choices=[('leve', 'Leve'), ('moderado', 'Moderado'), ('grave', 'Grave'), ('muy_grave', 'Muy Grave')], default='leve', max_length=20)),
                ('descripcion', models.TextField()),
                ('acciones_tomadas', models.TextField(blank=True, default='')),
                ('fecha_seguimiento', models.DateField(blank=True, null=True)),
                ('resuelto', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ano_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='core.anoescolar')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='core.estudiante')),
                ('profesor_reporta', models.ForeignKey(blank=True, limit_choices_to={'rol': 'profesor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Observador',
                'verbose_name_plural': 'Observadores',
                'db_table': 'observadores',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionColegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rector_nombre', models.CharField(blank=True, default='', max_length=200)),
                ('rector_cedula', models.CharField(blank=True, default='', max_length=20)),
                ('rector_firma', models.ImageField(blank=True, null=True, upload_to='colegios/firmas/')),
                ('mensaje_boletin', models.TextField(blank=True, default='')),
                ('escala_valoracion', models.TextField(blank=True, default='1.0 - 3.0: Bajo\n3.1 - 3.9: Básico\n4.0 - 4.5: Alto\n4.6 - 5.0: Superior')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('colegio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='core.colegio')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
                'db_table': 'configuraciones_colegio',
            },
        ),
        migrations.CreateModel(
            name='AgendaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('evento', 'Evento'), ('examen', 'Examen'), ('reunion', 'Reunión'), ('actividad', 'Actividad Extra'), ('entrega', 'Fecha de Entrega')], default='evento', max_length=20)),
                ('grado', models.CharField(blank=True, default='', help_text='Grados afectados (vacío = todos)', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ano_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.anoescolar')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'agenda_eventos',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Parcelador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('grado', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ano_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelador', to='core.anoescolar')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.materia')),
            ],
            options={
                'verbose_name': 'Parcelador',
                'verbose_name_plural': 'Parceladores',
                'db_table': 'parceladores',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('dia_semana', 'hora_inicio', 'ano_escolar', 'grado')},
            },
        ),
        migrations.CreateModel(
            name='Boletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('1', 'Periodo 1'), ('2', 'Periodo 2'), ('3', 'Periodo 3'), ('4', 'Periodo 4'), ('F', 'Final')], default='1', max_length=2)),
                ('promedio_general', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('lugar', models.IntegerField(default=0)),
                ('observaciones_generales', models.TextField(blank=True, default='')),
                ('asistencia_pct', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ano_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletines', to='core.anoescolar')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletines', to='core.estudiante')),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boletín',
                'verbose_name_plural': 'Boletines',
                'db_table': 'boletines',
                'unique_together': {('estudiante', 'ano_escolar', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('asistio', 'Asistió'), ('falta', 'Falta'), ('tarde', 'Llegó tarde'), ('justificado', 'Justificado')], default='asistio', max_length=20)),
                ('observacion', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ano_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='core.anoescolar')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='core.estudiante')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'db_table': 'asistencias',
                'ordering': ['-fecha'],
                'unique_together': {('estudiante', 'fecha')},
            },
        ),
    ]
